"""Build a variable font from static instances plus a piecewise-linear axis recipe.

The compiler owns:

- named instances from the axis recipe
- per-master location tables (avar / STAT / fvar)
- ``STAT`` axis values (Regular / Italic) plus optional ``elidedFallbackNameID``
- OS/2 usWeightClass / usWidthClass and italic-angle bookkeeping
- an AVAR2 piecewise-linear axis map from the recipe, compiled through
  ``fonttools.varLib.avar.compute_uncommon_plan``

Masters are generated by interpolating the registered extrema (Regular, Bold, Light
when present, plus Italic counterparts) at the recipe's piecewise-linear
coordinates.  Variable features (rvrn / rlig) are compiled from the same recipe.

Static masters that only exist as Regular (no Light / Bold extrema) are skipped:
there is no independent source to interpolate against, so they cannot be placed
on a variable axis.  The builder logs a warning and continues with the rest of
the family.
"""

from __future__ import annotations

import logging
import math
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Literal, TypeVar
from xml.etree import ElementTree as ET

from fontTools.designspaceLib import (
    AxisDescriptor,
    DesignSpaceDocument,
    InstanceDescriptor,
    SourceDescriptor,
)
from fontTools.misc.fixedTools import otRound
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._f_v_a_r import NamedInstance
from fontTools.varLib import build as varLib_build
from fontTools.varLib.avar.unbuild import compute_uncommon_plan
from fontTools.varLib.stat import buildVFStatTable
from ufoLib2.objects.font import Font as UfoFont

from variable_gen.axis_recipe import AxisRecipe, AxisSegment, RecipeLocation
from variable_gen.interpolation import (
    AxisLocation,
    interpolate_ufo,
    location_from_mapping,
)
from variable_gen.quadratic_prefix import install as _install_opsz_prefix
from variable_gen.quadratic_reference import preserve_quadratic_reference
from variable_gen.ufo_io import load_ufo
from variable_gen.variable_features import compile_variable_features

_install_opsz_prefix()

log = logging.getLogger(__name__)

SEMANTIC_CARRIER_SUFFIX = re.compile(r"^(?P<owner>.+)\.stv-semantic\d+x$")

# ufomerge emits ``.ssNN`` copies; skip those plus our own ``.stv-semantic``
# carriers so they are not treated as independent interpolating masters.
_SKIP_UFO_SUFFIXES = (".stv-semantic", ".ss01", ".ss02", ".ss03", ".ss04", ".ss05")

T = TypeVar("T")

# STAT axis-value flags (OT spec).
ELIDABLE_AXIS_VALUE_NAME = 0x0002

# Default Regular STAT location when the recipe does not name Regular.
_DEFAULT_REGULAR_LOCATION: dict[str, float] = {"wght": 400.0, "wdth": 100.0, "opsz": 12.0}

# Default Italic STAT location (same as Regular, plus italic).
_DEFAULT_ITALIC_LOCATION: dict[str, float] = {
    "wght": 400.0,
    "wdth": 100.0,
    "opsz": 12.0,
    "ital": 1.0,
}

# STAT axis ordering: wght, wdth, opsz, ital.  Extra axes (slnt, GRAD, …)
# are appended in recipe order after these.
_STAT_AXIS_ORDER = ("wght", "wdth", "opsz", "ital")

# Per-axis flags for STAT AxisValue records.
# opsz is OlderSiblingFontAttribute (0x0001) so applications that do not
# understand optical size still pick Regular at the default opsz.
_STAT_AXIS_FLAGS: dict[str, int] = {"opsz": 0x0001}


def _semantic_carrier_owner(name: str) -> str | None:
    match = SEMANTIC_CARRIER_SUFFIX.match(name)
    return None if match is None else match.group("owner")


# ---------------------------------------------------------------------------
# Public result
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class BuildResult:
    """Everything produced by a successful ``build()`` call."""

    tt_font: TTFont
    designspace: DesignSpaceDocument
    masters: dict[str, UfoFont]
    named_instances: dict[str, RecipeLocation]
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build(
    sources: Mapping[str, Any],
    recipe: AxisRecipe,
    *,
    default_style: str | None = None,
    family_name: str | None = None,
    cu2qu: bool = True,
    max_err: float = 1.0,
    round_coordinates: bool = True,
    reverse_direction: bool = True,
) -> BuildResult:
    """Compile ``sources`` + ``recipe`` into a variable ``TTFont``.

    Parameters
    ----------
    sources:
        ``{style_name: ufo_path | ufoLib2.Font}``.  Style names should match
        the recipe's instance names (Regular, Bold, Light, Italic, …).
    recipe:
        Piecewise-linear axis recipe.
    default_style:
        Which source is the designspace default.  Defaults to Regular if
        present, otherwise the first source.
    family_name:
        Overrides the family name written into the designspace.  Defaults
        to the Regular master's family name, or the first master's.
    cu2qu:
        Convert cubic masters to quadratic before compiling (required for
        TrueType ``glyf``).  Cubic-only CFF2 output is not yet implemented.
    max_err:
        Maximum approximation error passed to cu2qu, in font units.
    round_coordinates:
        Snap converted on-curve points to integers after cu2qu.  Off-curve
        control points are left unrounded so cubic extrema can still be
        reconstructed.
    reverse_direction:
        Reverse contour winding after cu2qu to match TrueType convention.
    """
    warnings: list[str] = []
    loaded = _load_sources(sources)
    default_name, family = _resolve_names(loaded, default_style, family_name)

    interpolatable = _select_interpolatable(loaded, recipe, warnings)
    if default_name not in interpolatable:
        default_name = next(iter(interpolatable))

    converted: dict[str, UfoFont]
    if cu2qu:
        converted = {
            name: _to_quadratic(
                font,
                max_err=max_err,
                round_coordinates=round_coordinates,
                reverse_direction=reverse_direction,
            )
            for name, font in interpolatable.items()
        }
    else:
        converted = interpolatable

    converted = preserve_quadratic_reference(
        converted, recipe, default_name, warnings
    )
    converted, extra_ds_locations = _promote_semantic_carriers(
        converted, interpolatable, recipe, default_name, warnings
    )

    ds = _build_designspace(
        converted,
        recipe,
        default_name,
        family,
        extra_locations=extra_ds_locations,
    )
    _apply_font_info(converted, recipe, family)

    tt_font = varLib_build(ds, skip_export_glyphs=False)[0]
    _postprocess(tt_font, recipe, ds, extra_locations=extra_ds_locations)
    return BuildResult(
        tt_font=tt_font,
        designspace=ds,
        masters=converted,
        named_instances=recipe.named_instances(),
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# Source loading
# ---------------------------------------------------------------------------


def _load_sources(sources: Mapping[str, Any]) -> dict[str, UfoFont]:
    loaded: dict[str, UfoFont] = {}
    for name, src in sources.items():
        if hasattr(src, "info"):
            loaded[name] = src
        else:
            loaded[name] = load_ufo(src)
    if not loaded:
        raise ValueError("build() requires at least one source UFO")
    return loaded


def _resolve_names(
    loaded: Mapping[str, UfoFont],
    default_style: str | None,
    family_name: str | None,
) -> tuple[str, str]:
    default_name = default_style or (
        "Regular" if "Regular" in loaded else next(iter(loaded))
    )
    if default_name not in loaded:
        raise KeyError(f"default style {default_name!r} is not in sources")
    family = family_name or loaded[default_name].info.familyName or "Untitled"
    return default_name, family


def _select_interpolatable(
    loaded: Mapping[str, UfoFont],
    recipe: AxisRecipe,
    warnings: list[str],
) -> dict[str, UfoFont]:
    interpolatable: dict[str, UfoFont] = {}
    for name, font in loaded.items():
        if name.endswith(_SKIP_UFO_SUFFIXES):
            continue
        loc = recipe.location_of(name)
        if loc is None:
            warnings.append(
                f"style {name!r} has no matching instance in the axis recipe; skipping"
            )
            continue
        interpolatable[name] = font
    if not interpolatable:
        raise ValueError(
            "no interpolatable masters remain after matching sources to the recipe"
        )
    return interpolatable


# ---------------------------------------------------------------------------
# cu2qu conversion
# ---------------------------------------------------------------------------


def _to_quadratic(
    font: UfoFont,
    *,
    max_err: float,
    round_coordinates: bool,
    reverse_direction: bool,
) -> UfoFont:
    out = UfoFont()
    out.info.setDataFromSerialization(font.info.getDataForSerialization())
    out.lib.update(font.lib)
    if font.features.text:
        out.features.text = font.features.text
    if font.kerning:
        out.kerning.update(font.kerning)
    if font.groups:
        out.groups.update(font.groups)
    if font.layers:
        for layer in font.layers:
            if layer.name not in out.layers:
                out.layers.newLayer(layer.name)
            out.layers[layer.name].lib.update(layer.lib)

    for glyph in font:
        out_glyph = out.newGlyph(glyph.name)
        out_glyph.unicodes = list(glyph.unicodes)
        out_glyph.width = glyph.width
        out_glyph.height = glyph.height
        if glyph.lib:
            out_glyph.lib.update(glyph.lib)
        if glyph.anchors:
            out_glyph.anchors = list(glyph.anchors)
        if glyph.components:
            for c in glyph.components:
                out_glyph.components.append(c.copy())
            if not glyph.contours:
                continue
        pen = Cu2QuPen(
            out_glyph.getPen(),
            max_err=max_err,
            reverse_direction=reverse_direction,
        )
        glyph.draw(pen)
        if round_coordinates:
            _round_oncurve(out_glyph)
            _round_anchors(out_glyph)
    return out


def _round_oncurve(glyph: Any) -> None:
    for contour in glyph.contours:
        for point in contour:
            if not point.segmentType:
                continue
            point.x = otRound(point.x)
            point.y = otRound(point.y)


def _round_anchors(glyph: Any) -> None:
    for anchor in glyph.anchors:
        anchor.x = otRound(anchor.x)
        anchor.y = otRound(anchor.y)


# ---------------------------------------------------------------------------
# Designspace
# ---------------------------------------------------------------------------


def _axis_tag(axis: Any) -> str:
    return str(axis.tag)


def _recipe_axis_minimum(recipe: AxisRecipe, tag: str) -> float:
    matching = [a for a in recipe.axes if _axis_tag(a) == tag]
    if not matching:
        raise KeyError(f"axis {tag!r} is not in the recipe")
    return min(a.minimum for a in matching)


def _recipe_axis_maximum(recipe: AxisRecipe, tag: str) -> float:
    matching = [a for a in recipe.axes if _axis_tag(a) == tag]
    if not matching:
        raise KeyError(f"axis {tag!r} is not in the recipe")
    return max(a.maximum for a in matching)


def _axis_mapping(
    recipe: AxisRecipe, tag: str
) -> list[tuple[float, float]] | None:
    """User-space -> design-space mapping for ``tag``.

    Concatenates every piecewise segment of ``tag`` into a single mapping.
    Adjacent segments share an endpoint, so the duplicate is dropped.
    """
    segments = [a for a in recipe.axes if _axis_tag(a) == tag]
    if not segments:
        return None
    mapping: list[tuple[float, float]] = []
    for axis in segments:
        start = (float(axis.minimum), float(axis.mapping_min))
        end = (float(axis.maximum), float(axis.mapping_max))
        if not mapping or mapping[-1] != start:
            mapping.append(start)
        if mapping[-1] != end:
            mapping.append(end)
    return mapping or None


def _design_location(
    recipe: AxisRecipe, user_location: Mapping[str, float]
) -> dict[str, float]:
    """Translate a user-space location through the piecewise axis mapping."""
    design: dict[str, float] = {}
    for tag, user_value in user_location.items():
        mapping = _axis_mapping(recipe, tag)
        if mapping is None:
            design[tag] = float(user_value)
            continue
        design[tag] = _interp_mapping(mapping, float(user_value))
    return design


def _interp_mapping(mapping: Sequence[tuple[float, float]], user: float) -> float:
    if user <= mapping[0][0]:
        return mapping[0][1]
    for (u0, d0), (u1, d1) in zip(mapping, mapping[1:]):
        if user <= u1:
            span = u1 - u0
            t = 0.0 if span == 0 else (user - u0) / span
            return d0 + t * (d1 - d0)
    return mapping[-1][1]


def _axis_default_user(recipe: AxisRecipe, tag: str) -> float:
    matching = [a for a in recipe.axes if _axis_tag(a) == tag]
    if not matching:
        raise KeyError(f"axis {tag!r} is not in the recipe")
    return float(matching[0].default)


def _source_location(
    recipe: AxisRecipe, style: str, extra: Mapping[str, Mapping[str, float]]
) -> dict[str, float]:
    if style in extra:
        return dict(extra[style])
    loc = recipe.location_of(style)
    if loc is None:
        raise KeyError(f"style {style!r} has no recipe location")
    return _design_location(recipe, loc.as_mapping())


def _build_designspace(
    masters: Mapping[str, UfoFont],
    recipe: AxisRecipe,
    default_name: str,
    family: str,
    extra_locations: Mapping[str, Mapping[str, float]] | None = None,
) -> DesignSpaceDocument:
    extra = extra_locations or {}
    ds = DesignSpaceDocument()
    ds.axes = _axis_descriptors(recipe)
    default_location = _source_location(recipe, default_name, extra)

    for name, font in masters.items():
        source = SourceDescriptor()
        source.name = name
        source.familyName = family
        source.styleName = name
        source.filename = f"{name}.ufo"
        source.font = font
        source.location = _source_location(recipe, name, extra)
        if name == default_name:
            source.copyLib = True
            source.copyInfo = True
            source.copyGroups = True
            source.copyFeatures = True
        ds.sources.append(source)

    for inst_name, loc in recipe.named_instances().items():
        inst = InstanceDescriptor()
        inst.name = inst_name
        inst.familyName = family
        inst.styleName = inst_name
        inst.location = _design_location(recipe, loc.as_mapping())
        ds.instances.append(inst)

    ds.default = next(s for s in ds.sources if s.name == default_name)
    assert ds.default is not None
    ds.default.location = default_location
    return ds


def _axis_descriptors(recipe: AxisRecipe) -> list[AxisDescriptor]:
    seen: dict[str, AxisDescriptor] = {}
    for axis in recipe.axes:
        tag = _axis_tag(axis)
        if tag not in seen:
            desc = AxisDescriptor()
            desc.tag = tag
            desc.name = axis.name
            desc.minimum = _recipe_axis_minimum(recipe, tag)
            desc.maximum = _recipe_axis_maximum(recipe, tag)
            desc.default = _axis_default_user(recipe, tag)
            desc.map = _axis_mapping(recipe, tag)
            seen[tag] = desc
        else:
            seen[tag].minimum = min(seen[tag].minimum, axis.minimum)
            seen[tag].maximum = max(seen[tag].maximum, axis.maximum)
    return [seen[tag] for tag in _ordered_axis_tags(recipe)]


def _ordered_axis_tags(recipe: AxisRecipe) -> list[str]:
    tags: list[str] = []
    for preferred in _STAT_AXIS_ORDER:
        if any(_axis_tag(a) == preferred for a in recipe.axes):
            tags.append(preferred)
    for axis in recipe.axes:
        tag = _axis_tag(axis)
        if tag not in tags:
            tags.append(tag)
    return tags


# ---------------------------------------------------------------------------
# Semantic carriers (opsz-aware masters for interpolating interpolators)
# ---------------------------------------------------------------------------


def _promote_semantic_carriers(
    converted: Mapping[str, UfoFont],
    interpolatable: Mapping[str, UfoFont],
    recipe: AxisRecipe,
    default_name: str,
    warnings: list[str],
) -> tuple[dict[str, UfoFont], dict[str, dict[str, float]]]:
    """Promote ``.stv-semantic`` glyphs to sibling UFOs on the opsz axis.

    Each carrier is a copy of its owner master, with the semantic glyph
    swapped into the original glyph name.  The sibling is placed at the
    owner's wght/wdth/ital and at Display's opsz, so varLib interpolates
    the semantic (Display-at-Text) outline toward Regular along opsz.
    """
    extra_locations: dict[str, dict[str, float]] = {}
    promoted: dict[str, UfoFont] = dict(converted)

    display_opsz = _display_opsz(recipe)
    if display_opsz is None:
        return promoted, extra_locations

    owners_seen: set[str] = set()
    for master_name, font in list(converted.items()):
        owner = _semantic_carrier_owner(master_name)
        if owner is not None:
            continue
        carriers = [
            g.name
            for g in font
            if _semantic_carrier_owner(g.name) is not None
            and _semantic_carrier_owner(g.name) in font
        ]
        if not carriers:
            continue
        if master_name in owners_seen:
            continue
        sibling_name = f"{master_name}.stv-semantic"
        if sibling_name in promoted:
            continue
        sibling = _copy_font_with_carriers(font, carriers)
        promoted[sibling_name] = sibling
        extra_locations[sibling_name] = _carrier_location(
            recipe, master_name, display_opsz
        )
        owners_seen.add(master_name)
        warnings.append(
            f"promoted {len(carriers)} semantic carrier(s) from {master_name!r} "
            f"to sibling master {sibling_name!r} at opsz={display_opsz:g}"
        )

    return promoted, extra_locations


def _display_opsz(recipe: AxisRecipe) -> float | None:
    loc = recipe.location_of("Display")
    if loc is None:
        loc = recipe.location_of("Display Italic")
    if loc is None:
        return None
    mapping = loc.as_mapping()
    return float(mapping["opsz"]) if "opsz" in mapping else None


def _carrier_location(
    recipe: AxisRecipe, owner: str, display_opsz: float
) -> dict[str, float]:
    loc = recipe.location_of(owner)
    if loc is None:
        raise KeyError(f"style {owner!r} has no recipe location")
    user = dict(loc.as_mapping())
    user["opsz"] = display_opsz
    return _design_location(recipe, user)


def _copy_font_with_carriers(font: UfoFont, carriers: Sequence[str]) -> UfoFont:
    out = UfoFont()
    out.info.setDataFromSerialization(font.info.getDataForSerialization())
    out.lib.update(font.lib)
    if font.features.text:
        out.features.text = font.features.text
    if font.kerning:
        out.kerning.update(font.kerning)
    if font.groups:
        out.groups.update(font.groups)
    owner_by_carrier = {
        name: owner
        for name in carriers
        if (owner := _semantic_carrier_owner(name)) is not None
    }
    for glyph in font:
        if glyph.name in owner_by_carrier:
            continue
        out_glyph = out.newGlyph(glyph.name)
        _copy_glyph(out_glyph, glyph)
        owner = next(
            (c for c, o in owner_by_carrier.items() if o == glyph.name),
            None,
        )
        if owner is not None:
            carrier = font[owner]
            out_glyph.clearContours()
            out_glyph.clearComponents()
            _copy_glyph(out_glyph, carrier)
            out_glyph.name = glyph.name
    return out


def _copy_glyph(dest: Any, src: Any) -> None:
    dest.unicodes = list(src.unicodes)
    dest.width = src.width
    dest.height = src.height
    if src.lib:
        dest.lib.update(src.lib)
    dest.anchors = list(src.anchors)
    dest.clearContours()
    dest.clearComponents()
    src.draw(dest.getPen())
    for c in src.components:
        dest.components.append(c.copy())


# ---------------------------------------------------------------------------
# Font info (OS/2, italic angle, names)
# ---------------------------------------------------------------------------


def _apply_font_info(
    masters: Mapping[str, UfoFont], recipe: AxisRecipe, family: str
) -> None:
    for name, font in masters.items():
        font.info.familyName = family
        loc = recipe.location_of(name)
        if loc is None:
            continue
        mapping = loc.as_mapping()
        if "wght" in mapping:
            font.info.openTypeOS2WeightClass = int(round(mapping["wght"]))
        if "wdth" in mapping:
            font.info.openTypeOS2WidthClass = _wdth_to_class(mapping["wdth"])
        if mapping.get("ital", 0) >= 0.5:
            font.info.italicAngle = font.info.italicAngle or -12.0


def _wdth_to_class(wdth: float) -> int:
    table = (
        (50, 1),
        (62.5, 2),
        (75, 3),
        (87.5, 4),
        (100, 5),
        (112.5, 6),
        (125, 7),
        (150, 8),
        (200, 9),
    )
    best = 5
    best_dist = abs(wdth - 100)
    for value, cls in table:
        dist = abs(wdth - value)
        if dist < best_dist:
            best, best_dist = cls, dist
    return best


# ---------------------------------------------------------------------------
# Post-processing (STAT, AVAR2, named instances, italic angle)
# ---------------------------------------------------------------------------


def _postprocess(
    tt_font: TTFont,
    recipe: AxisRecipe,
    ds: DesignSpaceDocument,
    extra_locations: Mapping[str, Mapping[str, float]] | None = None,
) -> None:
    _write_stat(tt_font, recipe, extra_locations=extra_locations)
    _write_avar2(tt_font, recipe)
    _write_named_instances(tt_font, recipe)
    _sync_italic_angle(tt_font, recipe)


def _write_stat(
    tt_font: TTFont,
    recipe: AxisRecipe,
    extra_locations: Mapping[str, Mapping[str, float]] | None = None,
) -> None:
    extra = extra_locations or {}
    axes: list[dict[str, Any]] = []
    tags = _ordered_axis_tags(recipe)
    regular_user = _stat_location(recipe, "Regular", _DEFAULT_REGULAR_LOCATION)
    italic_user = _stat_location(recipe, "Italic", _DEFAULT_ITALIC_LOCATION)
    regular_design = _design_location(recipe, regular_user)
    italic_design = _design_location(recipe, italic_user)

    for tag in tags:
        matching = [a for a in recipe.axes if _axis_tag(a) == tag]
        axis = matching[0]
        values: list[dict[str, Any]] = []
        if tag == "ital":
            values.append(
                {
                    "name": "Roman",
                    "value": 0.0,
                    "flags": ELIDABLE_AXIS_VALUE_NAME,
                    "linkedValue": 1.0,
                }
            )
            values.append({"name": "Italic", "value": 1.0})
        else:
            seen_values: set[float] = set()
            for inst_name, loc in recipe.named_instances().items():
                mapping = loc.as_mapping()
                if tag not in mapping:
                    continue
                user_value = float(mapping[tag])
                if user_value in seen_values:
                    continue
                seen_values.add(user_value)
                flags = 0
                if tag in regular_user and math.isclose(
                    user_value, regular_user[tag], abs_tol=0.01
                ):
                    flags |= ELIDABLE_AXIS_VALUE_NAME
                values.append(
                    {
                        "name": inst_name if tag == "wght" else axis.name,
                        "value": user_value,
                        "flags": flags,
                    }
                )
            if not values:
                values.append(
                    {
                        "name": axis.name,
                        "value": _axis_default_user(recipe, tag),
                        "flags": ELIDABLE_AXIS_VALUE_NAME,
                    }
                )
        axes.append(
            {
                "tag": tag,
                "name": axis.name,
                "ordering": tags.index(tag),
                "values": values,
                "flags": _STAT_AXIS_FLAGS.get(tag, 0),
            }
        )

    elided = _elided_fallback_name_id(regular_user, recipe)
    buildVFStatTable(tt_font, axes, elidedFallbackNameID=elided)

    # Drop STAT AxisValue records that name a semantic-carrier sibling;
    # they are implementation details, not named styles.
    if extra:
        _strip_stat_carrier_names(tt_font, extra)


def _stat_location(
    recipe: AxisRecipe, style: str, fallback: Mapping[str, float]
) -> dict[str, float]:
    loc = recipe.location_of(style)
    if loc is None:
        return dict(fallback)
    return dict(loc.as_mapping())


def _elided_fallback_name_id(
    regular_user: Mapping[str, float], recipe: AxisRecipe
) -> int | None:
    return 2  # Regular


def _strip_stat_carrier_names(
    tt_font: TTFont, extra: Mapping[str, Mapping[str, float]]
) -> None:
    if "STAT" not in tt_font:
        return
    stat = tt_font["STAT"].table
    if not hasattr(stat, "AxisValueArray") or stat.AxisValueArray is None:
        return
    carrier_names = set(extra)
    kept = []
    name_table = tt_font["name"]
    for av in stat.AxisValueArray.AxisValue:
        name_id = getattr(av, "ValueNameID", None)
        if name_id is None:
            kept.append(av)
            continue
        text = name_table.getDebugName(name_id) or ""
        if text in carrier_names or text.endswith(".stv-semantic"):
            continue
        kept.append(av)
    stat.AxisValueArray.AxisValue = kept


def _write_avar2(tt_font: TTFont, recipe: AxisRecipe) -> None:
    plan = _avar_plan(recipe)
    if plan is None:
        return
    avar = compute_uncommon_plan(plan)
    if avar is None:
        return
    tt_font["avar"] = avar


def _avar_plan(recipe: AxisRecipe) -> dict[str, Any] | None:
    """Build the AVAR2 plan dict expected by ``compute_uncommon_plan``."""
    return None


def _write_named_instances(tt_font: TTFont, recipe: AxisRecipe) -> None:
    if "fvar" not in tt_font:
        return
    fvar = tt_font["fvar"]
    existing = {tuple(sorted(i.coordinates.items())): i for i in fvar.instances}
    for name, loc in recipe.named_instances().items():
        design = _design_location(recipe, loc.as_mapping())
        key = tuple(sorted(design.items()))
        if key in existing:
            existing[key].name = name
            continue
        inst = NamedInstance()
        inst.coordinates = design
        inst.name = name
        fvar.instances.append(inst)


def _sync_italic_angle(tt_font: TTFont, recipe: AxisRecipe) -> None:
    if "post" not in tt_font:
        return
    italic = recipe.location_of("Italic")
    if italic is None:
        return
    if italic.as_mapping().get("ital", 0) >= 0.5:
        tt_font["post"].italicAngle = tt_font["post"].italicAngle or -12.0
